### PR TITLE
[common]: Remove logPersistence as it can be achieved with existing values

### PR DESCRIPTION
**Pull request by adberger**
**What this PR does**:

Removes `logPersistence` functionality as it can be achieved with `volumeMounts` & `extraVolumeClaimTemplates` and is buggy anyway.

**Checklist**:

- [x] Pull Request title in format `[chart]: Changed Something`
- [x] Updated documentation in the  `README.md.gotmpl` file and executed `helm-docs` 
- [x] Chart Version bumped
- [x] All commits are signed-off

### CODE REVIEW

**Comment by janfuhrer** [comment]
According to the [contributing guidelines](https://github.com/bedag/helm-charts/blob/master/CONTRIBUTING.md), we should have a changelog in the README.
Can you add this?

**Review by janfuhrer — CHANGES_REQUESTED** [review]
update artifacthub annotations

**Comment by adberger** [comment]
> According to the [contributing guidelines](https://github.com/bedag/helm-charts/blob/master/CONTRIBUTING.md), we should have a changelog in the README. Can you add this?

README.md.gotmpl was missing completly, fixed it.

**Comment by adberger** [comment]
> update artifacthub annotations

done, hope it's correct like this.

**Review by janfuhrer — APPROVED** [review]
lgtm

**Pull request merged**
