### PR TITLE
[common]: add ingress defaultBackend

### PR DESCRIPTION
**Pull request by TobyTheHutt**
**What this PR does**:
This PR enables the possibility to define a default Backend for ingresses.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
none

**Notes for Reviewer**:

**Checklist**:

- [x] Pull Request title in format `[chart]: Changed Something`
- [x] Updated documentation in the  `README.md.gotmpl` file and executed `helm-docs` 
- [x] Chart Version bumped
- [x] All commits are signed-off

### CODE REVIEW

**Comment by brjos** [comment]
Thanks for contributing @TobyTheHutt!

According to the [ingress doc for DefaultBackends](https://kubernetes.io/docs/concepts/services-networking/ingress/#default-backend):
`The defaultBackend is conventionally a configuration option of the Ingress controller and is not specified in your Ingress resources`.

If you intend to create an ingress resource that is backed by a single Service, then you should assure, that no rules are set in the ingress resource, if I understand the [doc](https://kubernetes.io/docs/concepts/services-networking/ingress/#single-service-ingress) correct:
`You can also do this with an Ingress by specifying a default backend with no rules.`

**Comment by TobyTheHutt** [comment]
Hi @brjos 
Thank you for reading the documentation to me! Seriously, I overlooked this part.
I agree with you that this modification would only be useful in very specific use cases, as shown in the examples of the page. How do we proceed with this PR?

**Comment by brjos** [comment]
I'd say: because you already invested time: why not just make sure that no `rules` can be created when `$ingress.defaultBackend` is defined; or alternatively: close the PR

**Comment by TobyTheHutt** [comment]
@brjos I made the options exclusive, so that only one of `rules` or `defaultBackend` can be defined. Please check the PR again.

**Review by brjos — APPROVED** [review]
LGTM

**Pull request merged**
